name: academa_streaming_platform
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  flutter_svg: ^2.0.17
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  provider: ^6.1.5
  camera: ^0.11.1
  rtmp_broadcaster: ^2.3.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^7.1.1
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0
  video_player: ^2.9.5
  cloud_firestore: ^5.6.8
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  flutter_secure_storage: ^4.2.1
  camerawesome: ^2.5.0
  intl: ^0.19.0

dev_dependencies:
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: lib/config/assets/academa_icon.png

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/config/assets/
    - .env

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: lib/config/fonts/SF-Pro-Display-Bold.otf
          weight: 100
        - asset: lib/config/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: lib/config/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: lib/config/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/config/fonts/SF-Pro-Display-Bold.otf
          weight: 700
